version: '3.5'

services:

  turistandopb-api:
    container_name: turistandopb-api
    build:
      context: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: postgres-turistandopb-api
    image: postgres:12.3
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-turistandopb-api:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres

volumes:
  postgres-turistandopb-api:
